version: '3'

services:
    ros-melodic-base:
        build:
            context: .
            dockerfile: Dockerfile.base
        image: ros-melodic-base
    
    ros-melodic-industrial:
        build: 
            context: .
            dockerfile: Dockerfile.industrial
            args: 
                - BASE_IMAGE=ros-melodic-base
        image: ros-melodic-industrial
        runtime: nvidia
        environment: 
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - XAUTHORITY=/tmp/.docker.xauth
        stdin_open: true
        privileged: true
        tty: true
        network_mode: "host"
        volumes:
            - /tmp/.docker.xauth:/tmp/.docker.xauth 
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - $HOME/.Xauthority:/root/.Xauthority
        
        command: 
            - roscore