
services:

    jammy_humble_recovery_test:
        image: ghcr.io/ipa-vsp/docker_envs:22.04-humble
        # user: admin:admin
        stdin_open: true
        privileged: true
        tty: true
        networks:
            vsp_net:
                ipv4_address: 172.28.0.2
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            - ../../../recovery/colcon_recovery_ws/src:/home/admin/colcon_ws/src
        environment:
            - DISPLAY=$DISPLAY
            - ROS_DOMAIN_ID=73
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"
    
    jammy_humble_runtime_test:
        image: ghcr.io/ipa-vsp/docker_envs:22.04-humble
        # user: admin:admin
        stdin_open: true
        privileged: true
        tty: true
        networks:
            vsp_net:
                ipv4_address: 172.28.0.3
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            - ../../../recovery/runtime_reasoning:/home/admin/colcon_ws/src
        environment:
            - DISPLAY=$DISPLAY
            - ROS_DOMAIN_ID=73
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"
    
    
    jammy_humble_unitree_test:
        image: ghcr.io/ipa-vsp/docker_envs:22.04-humble-moveit
        # user: admin:1001
        stdin_open: true
        privileged: true
        tty: true
        networks:
            vsp_net:
                ipv4_address: 172.28.0.3
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            - ../../../unitree/colcon_ws/src:/home/admin/colcon_ws/src
        environment:
            - DISPLAY=$DISPLAY
            - ROS_DOMAIN_ID=73
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"

networks:
    vsp_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
